### ISSUE TITLE
cannot find module extra

### ISSUE THREAD

**Issue by RFlintstone** [bostrot/telegram-support-bot#2] opened 2017-12-18 21:04 UTC
Hello Bostrot, 

My host (Heroku.com) works with procfiles and package.json files. This means if i want to use your support bot (what i definitly want to use) i need to have the scripts, dependencies ect.

I now have:
https://github.com/Flintstone2020/telegram-support-bot/blob/master/bin/support.js
and this:
https://github.com/Flintstone2020/telegram-support-bot/blob/master/package.json

And that almost works. 
I currently have the following output:

```
2017-12-18T21:01:49.186666+00:00 heroku[web.1]: State changed from crashed to starting
2017-12-18T21:01:51.344000+00:00 heroku[web.1]: Starting process with command `npm start`
2017-12-18T21:01:56.250763+00:00 app[web.1]: 
2017-12-18T21:01:56.250786+00:00 app[web.1]: > telegraf-bot@3.17.2 start /app
2017-12-18T21:01:56.250787+00:00 app[web.1]: > node bin/support.js
2017-12-18T21:01:56.250787+00:00 app[web.1]: 
2017-12-18T21:01:56.595197+00:00 app[web.1]: module.js:557
2017-12-18T21:01:56.595220+00:00 app[web.1]:     throw err;
2017-12-18T21:01:56.595221+00:00 app[web.1]:     ^
2017-12-18T21:01:56.595222+00:00 app[web.1]: 
2017-12-18T21:01:56.595223+00:00 app[web.1]: Error: Cannot find module 'extra'
2017-12-18T21:01:56.595224+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:555:15)
2017-12-18T21:01:56.595224+00:00 app[web.1]:     at Function.Module._load (module.js:482:25)
2017-12-18T21:01:56.595225+00:00 app[web.1]:     at Module.require (module.js:604:17)
2017-12-18T21:01:56.595226+00:00 app[web.1]:     at require (internal/module.js:11:18)
2017-12-18T21:01:56.595226+00:00 app[web.1]:     at Object.<anonymous> (/app/bin/support.js:30:15)
2017-12-18T21:01:56.595227+00:00 app[web.1]:     at Module._compile (module.js:660:30)
2017-12-18T21:01:56.595227+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:671:10)
2017-12-18T21:01:56.595228+00:00 app[web.1]:     at Module.load (module.js:573:32)
2017-12-18T21:01:56.595229+00:00 app[web.1]:     at tryModuleLoad (module.js:513:12)
2017-12-18T21:01:56.595229+00:00 app[web.1]:     at Function.Module._load (module.js:505:3)
2017-12-18T21:01:56.603586+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2017-12-18T21:01:56.603911+00:00 app[web.1]: npm ERR! errno 1
2017-12-18T21:01:56.604980+00:00 app[web.1]: npm ERR! telegraf-bot@3.17.2 start: `node bin/support.js`
2017-12-18T21:01:56.605102+00:00 app[web.1]: npm ERR! Exit status 1
2017-12-18T21:01:56.605256+00:00 app[web.1]: npm ERR! 
2017-12-18T21:01:56.605393+00:00 app[web.1]: npm ERR! Failed at the telegraf-bot@3.17.2 start script.
2017-12-18T21:01:56.605482+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2017-12-18T21:01:56.611406+00:00 app[web.1]: 
2017-12-18T21:01:56.611611+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2017-12-18T21:01:56.611698+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2017-12-18T21_01_56_606Z-debug.log
2017-12-18T21:01:56.704770+00:00 heroku[web.1]: Process exited with status 1
2017-12-18T21:01:56.716577+00:00 heroku[web.1]: State changed from starting to crashed
```

Can you help me solve this problem?

Kind regards,
Ruben

**Comment by bostrot** [comment] 2017-12-20 21:22
Normally this means that the node module "extra" is not installed. Usually it is installed automatically as a dependency. You can install it with `npm install extra`.

**Comment by RFlintstone** [comment] 2017-12-21 08:53
Hi Bostrot,

This didn't work, I get the same output. Can you take a look at my files?
URL: https://github.com/Flintstone2020/telegram-support-bot

-Ruben

**Comment by bostrot** [comment] 2017-12-22 10:15
First look at the output of following and asure that the version of node is past 6.2. Then that none of these returns nothing.

    node -v
    npm -v
    which npm
    which node
    echo $NODE_PATH

About your fork: Never publish your bot token. Everyone could use it. You should revoke your current one and get a new under BotFather.

**Comment by RFlintstone** [comment] 2017-12-22 22:11
Hi bostrot, 

Im currently testing the bot so im not revoking this token _yet_, i will as soon as this is fixed.
About the commands you gave me only `echo $NODE_PATH` showed nothing.

These are the outputs:
```
node -v = v9.3.0
npm -v = 5.5.1
which npm = /app/.heroku/node/bin/npm
which node = /app/.heroku/node/bin/node
echo $NODE_PATH = blank
```

Kind regards,
Ruben

**Comment by bostrot** [comment] 2017-12-22 22:15
All right. Just wanted to point this out. 
npm install --global --verbose extra
When running this you will probably get a path like 
/opt/lib/node_modules/extra

Take this path and set the $NODE_PATH
export NODE_PATH=/opt/lib/node_modules

Then try everything again

**Comment by RFlintstone** [comment] 2017-12-22 22:21
Hi, 

I got the followig output, what do i need to do?:
https://pastebin.com/G9JxuEeB

-Ruben

**Comment by bostrot** [comment] 2017-12-22 22:30
Before I look into your output check following: Go to the directory where the file support.js is located. Perform `npm install`. If it still does not either `export NODE_PATH=/app/.heroku/node/bin/node_modules` or `export NODE_PATH=/app/.heroku/node/lib/node_modules` could solve your problem.
Beside that, how did you install Node.JS? If all that won't work you can try to uninstall it completly and install it with node's own doc https://nodejs.org/en/download/package-manager/

**Comment by RFlintstone** [comment] 2017-12-28 14:52
It didn't work :(

**Comment by bostrot** [comment] 2018-02-26 10:41
Do you still have this problem?

**Comment by RFlintstone** [comment] 2018-02-26 12:50
Yes, I do still have it, to be fare I gave it up after asking people on stackoverflow.

Can't you try to set it up on Heroku and then share the repo/data??

**Comment by bostrot** [comment] 2018-02-28 20:17
All right. I just made a new branch for [Heroku](https://github.com/bostrot/telegram-support-bot/tree/heroku). I also just confirmed that it works with all needed commands. Test it and reply how it went.

**Comment by RFlintstone** [comment] 2018-03-01 09:35
Ok, just replace the current .json ?

**Comment by bostrot** [comment] 2018-03-01 10:59
No, there are multiple differences in the support.js file to. I would recommend to re-fork the project.
Also because the Telegram API updated and the new files are including all new updates.

**Comment by RFlintstone** [comment] 2018-03-01 11:32
How can i setup the telegram token and name without making it public on github?

**Comment by RFlintstone** [comment] 2018-03-01 11:33
Its also saying: 
2018-03-01T11:32:43.523617+00:00 app[web.1]: Failed to fetch updates. Waiting: 1s 404: Not Found

I suppose that's is because i didn't do the setup yet(?)

**Comment by bostrot** [comment] 2018-03-01 11:37
Contact me over Telegram @Bostrot please.

**Comment by bostrot** [comment] 2018-03-01 12:42
Wrong branch. Closing.

**Closed by bostrot** 2018-03-01 12:42 UTC
Labels: question

**Comment by RFlintstone** [comment] 2018-04-21 15:53
@MartinDelille do you use heroku?

**Comment by MartinDelille** [comment] 2018-04-22 11:57
@RFlintstone Yes but I had this issue locally. I finally fixed it: it was just a token copy/paste error!
