### ISSUE TITLE
Multilingual

### ISSUE THREAD

**Issue by IN80** [bostrot/telegram-support-bot#119] opened 2022-09-20 11:48 UTC
Make the bot multilingual. The user chooses in which language he wants to communicate. Depending on how the language is chosen, he receives an automatic message in that language.
I hope I explained clearly.

**Comment by bostrot** [comment] 2022-09-20 12:24
Duplicate of #27

**Comment by IN80** [comment] 2022-09-20 13:20
Only I do not quite understand how the bot will work in several languages. I opened the link you mentioned, but there is no solution to the problem.

**Comment by bostrot** [comment] 2022-09-20 19:40
Yes but you do not need to open a second feature request if there already is one for that.

**Comment by IN80** [comment] 2022-09-20 19:54
The idea is this: The user writes in Spanish. The bot saw that he wrote in Spanish and answered him in Spanish or first in English, and then the words "Hello" and "Respectfully" are already substituted in Spanish.

**Comment by bostrot** [comment] 2022-12-08 09:59
Closing as it is a duplicate.

**Closed by bostrot** 2022-12-08 09:59 UTC
Labels: feature
