### ISSUE TITLE
Error: 403: Forbidden: bot was blocked by the user

### ISSUE THREAD

**Issue by kultpro** [bostrot/telegram-support-bot#55] opened 2021-05-19 17:14 UTC
I encountered the following errors

* The bot only works with nodejs v10. 24. 1 (npm v6. 14. 12)
* If the user deletes the bot and checks "stop bot", the bot crashes with errors:

      Error:
      Failed to process updates. Error: Telegraf: "reply" isn't available for "undefined::"
          at TelegrafContext.assert (/root/telegram-support-bot/node_modules/telegraf/context.js:172:13)
          at TelegrafContext.reply (/root/telegram-support-bot/node_modules/telegraf/context.js:314:10)
          at Telegraf.bot.catch [as handleError] (/root/telegram-support-bot/src/index.ts:94:7)
          at middleware.catch (/root/telegram-support-bot/node_modules/telegraf/telegraf.js:171:55)
          at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by bostrot** [comment] 2021-05-20 07:07
Just experienced something similar with this addition:

    bot002    | === UNHANDLED REJECTION ===
    bot002    | 'Sat May 15 2021 21:04:25 GMT+0000 (Coordinated Universal Time): Error: 403: Forbidden: bot was blocked by the user\n' +
    bot002    |   '    at /bot/node_modules/telegraf/core/network/client.js:281:17\n' +
    bot002    |   '    at processTicksAndRejections (node:internal/process/task_queues:94:5)'

It continues after restarting the bot so it probably hangs with the telegram polling and crashes before marking it as read.. 

I guess we need some checks whether the bot can actually write the user and still mark the message.

I could not reproduce that the bot works only with nodejs v10.24.1. Are you missing some dependencies? What is your log?

**Comment by kultpro** [comment] 2021-05-20 10:45
This started happening after the previous update. Before that, it was put without problems. I install NVM, and then go through the node js versions. In all cases, except for version 10, errors appeared. Perhaps you are right and it's about dependencies. 

Thank you for your help and quick response!

**Comment by kultpro** [comment] 2021-05-20 10:48
> It continues after restarting the bot so it probably hangs with the telegram polling and crashes before marking it as read..
> 
> I guess we need some checks whether the bot can actually write the user and still mark the message.

If you just delete the bot, then when you reply to the user, the message comes without problems. If the "stop bot" checkbox is checked when deleting a bot,then this is the error.

**Comment by bostrot** [comment] 2021-05-21 07:59
> In all cases, except for version 10, errors appeared

Could you some logs or the error messages?

> when deleting a bot,then this is the error

I will try to create a check if the bot is blocked and see if it still does the same.

**Comment by kultpro** [comment] 2021-05-25 13:11
> Could you share some logs or the error messages?

Okay, I'll do it soon

**Comment by kultpro** [comment] 2021-05-25 13:15
Sometimes your application throws an error of the "Error" type, after which it can continue to work, or it can "hang", and in this case, until I restart, new messages from users do not come. Today there was an error: "b4Error". In debug.log, they are usually not present, or they are also referred to simply as "Error". If I run the app in dev mode, will I collect the errors in a more detailed format?

**Comment by bostrot** [comment] 2021-05-25 16:09
If it shows only "Error" then the actual error message is empty which makes it very hard to debug. Do you know what happened before it showed the message?

Running in dev mode could give you more details but I can't say for sure that it shows the actual error message then.

**Comment by bostrot** [comment] 2021-05-25 16:28
Looked into it a bit closer and it seems that commit 9f44bd6d19272a8bb0bc5aae08d507e5c1526c22 (from issue #52) is the reason:

    ctx.reply('Message is not sent due to an error.');

The bot tries to send a message when an error occurs to the user but as is is blocked it gets into a loop..

**Comment by bostrot** [comment] 2021-05-25 16:39
Commit 27a707f5adb46284c99abdf30167fa24123f9ec8 should be a hotfix for now (for Forbidden: bot was blocked by the user) which catches any error that is thrown by sending an error message to a user that has blocked the bot. Could you try it?

Also regarding the error messages: `npm run dev` should give you a little more detail about where they come from.

**Comment by kultpro** [comment] 2021-05-25 20:29
> Commit [27a707f](https://github.com/bostrot/telegram-support-bot/commit/27a707f5adb46284c99abdf30167fa24123f9ec8) should be a hotfix for now (for Forbidden: bot was blocked by the user) which catches any error that is thrown by sending an error message to a user that has blocked the bot. Could you try it?
> 
> Also regarding the error messages: `npm run dev` should give you a little more detail about where they come from.

Thanks! I will test it.

**Comment by kultpro** [comment] 2021-05-26 23:11
Updated normally, when the bot is blocked, the app no longer crashes

**Comment by kultpro** [comment] 2021-05-26 23:14
Application installation errors with the latest version of node js (installed via NVM) - Centos 7
https://xpaste.pro/en/p/4fHOS2Db

**Comment by bostrot** [comment] 2021-05-27 09:33
Thanks for testing and providing the log.

This seems rather like a better-sqlite3 error. Could you try installing it seperately?

`npm install better-sqlite3 --save`

in your working directory.

**Comment by kultpro** [comment] 2021-05-27 10:18
> This seems rather like a better-sqlite3 error. Could you try installing it seperately?
> 
> `npm install better-sqlite3 --save`
> 
> in your working directory.

Similar errors again
https://xpaste.pro/en/p/HvKHfyWp

**Comment by bostrot** [comment] 2021-05-28 07:35
This is a better-sqlite3 build error. Try installing build tools `sudo apt-get install build-essential` and if that doesn't work check out their github to find a solution.

**Closed** 2021-07-11 05:21 UTC
Labels: bug

**Comment by CodeQuit** [comment] 2022-06-25 10:07
need fix

**Comment by bostrot** [comment] 2022-06-25 10:10
> need fix

@CodeQuit This is already fixed.

You get the message when the users blocks/stops the bot. There is nothing you can do once that happened.
