### ISSUE TITLE
Support tickets do not open again when new messages from the same ID arrive

### ISSUE THREAD

**Issue by pilotseye** [bostrot/telegram-support-bot#19] opened 2019-06-25 07:36 UTC
**Is your feature request related to a problem? Please describe.**
It seems that once a ticket has been closed (after replying) it does not open again, when new messages arrive from the same ID.

**Describe the solution you'd like**
Either reopen closed tickets when new messages arrive from the same ID or keep them open until closed manually by a support agent.

**Comment by bostrot** [comment] 2019-06-29 10:18
I am not able to reproduce this issue. Do you use the latest commit?

What I did was sending a message to the bot, closing with `/close` feply cmd from staff chat; sending message to bot again.

Can you confirm this works?

**Comment by pilotseye** [comment] 2019-06-29 10:53
Thanks, does exactly what it should do in the latest commit :)

**Closed** 2019-06-29 17:05 UTC
Labels: bug
